-- CreateTable
CREATE TABLE `RAX_USER` (
    `RAX_U_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `RAX_U_USER_ID` VARCHAR(15) NOT NULL,
    `RAX_U_USER_NAME` VARCHAR(15) NULL,
    `RAX_U_UUID` VARCHAR(16) NULL,
    `RAX_U_PAR_NAME` VARCHAR(15) NULL,
    `RAX_U_EMAIL` TEXT NULL,
    `RAX_U_PWD` VARCHAR(20) NULL,
    `RAX_U_TEL` VARCHAR(13) NULL,
    `RAX_U_DEPT` VARCHAR(10) NULL,
    `RAX_U_ADDR` TEXT NULL,
    `RAX_U_BIRTH` DATETIME(3) NULL,
    `RAX_U_PAR_BIRTH` DATETIME(3) NULL,
    `RAX_U_DEPT_ROLE` VARCHAR(3) NULL,
    `RAX_U_STATUS` VARCHAR(1) NULL,

    UNIQUE INDEX `RAX_USER_RAX_U_USER_ID_key`(`RAX_U_USER_ID`),
    PRIMARY KEY (`RAX_U_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
